# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cpods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for cpods

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React' , :subspecs => [
      'CxxBridge',
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport'
  ], :path => '../node_modules/react-native'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'cpodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
